apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeops-dashboard
  labels:
    app: kubeops-dashboard
spec:
  selector:
    matchLabels:
      app: kubeops-dashboard
  template:
    metadata:
      labels:
        app: kubeops-dashboard
    spec:
      containers:
        - name: whitelist
          image: pooncheebean/kubeops-dashboard:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: kubeops-dashboard
  labels:
    app: kubeops-dashboard
spec:
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: kubeops-dashboard